name: Test Automation Workflow

on:
  schedule:
  - cron: 30 23 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build project
      run: mvn clean compile

    - name: Running test automation framework with Maven
      run: mvn test -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true
      
    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
       name: test-logs
       path: logs/

    - name: Upload Test reports
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
       name: test-reports
       path: target/extent-report/

    - name: Upload screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
       name: screenshots
       path: screenshots/ 

    - name: Copy report to GP folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R target/extent-report/report.html public/extent-reports/
        cp -R target/extent-report/screenshots/ public/extent-reports/screenshots/
        ls -l
      
    - name: Deploy
      if: always()
      uses: actions/deploy-pages@v4.0.5
      with:
       folder: public/extent-reports/
       token: ${{ secrets.secret }}
       clean: true

    - name: Test Execution Status
      run: echo "Test execution completed"
    
